Opentelemetry requirements in Python client (#1437)
## Description of changes

*Summarize the changes made by this PR.*
 - Improvements & Bug fixes
   - Python client now has correct dependencies.

## Test plan
*How are these changes tested?*

Prior to this change (in a virtualenv with only `chromadb-client`
installed):
```python
import chromadb

client = chromadb.HttpClient()

client.create_collection('test1231231232321')


File ~/experiments/chroma-experiments/client-embedding-f-issue-1429/venv/lib/python3.11/site-packages/chromadb/api/fastapi.py:36
     15 from chromadb.api.types import (
     16     DataLoader,
     17     Documents,
   (...)
     31     validate_batch,
     32 )
     33 from chromadb.auth import (
     34     ClientAuthProvider,
     35 )
---> 36 from chromadb.auth.providers import RequestsClientAuthProtocolAdapter
     37 from chromadb.auth.registry import resolve_provider
     38 from chromadb.config import DEFAULT_DATABASE, DEFAULT_TENANT, Settings, System

File ~/experiments/chroma-experiments/client-embedding-f-issue-1429/venv/lib/python3.11/site-packages/chromadb/auth/providers.py:19
     17 from chromadb.auth.registry import register_provider, resolve_provider
     18 from chromadb.config import System
---> 19 from chromadb.telemetry.opentelemetry import (
     20     OpenTelemetryGranularity,
     21     trace_method,
     22 )
     24 T = TypeVar("T")
     26 logger = logging.getLogger(__name__)

File ~/experiments/chroma-experiments/client-embedding-f-issue-1429/venv/lib/python3.11/site-packages/chromadb/telemetry/opentelemetry/__init__.py:5
      2 from enum import Enum
      3 from typing import Any, Callable, Dict, Optional, Sequence, Union
----> 5 from opentelemetry import trace
      6 from opentelemetry.sdk.resources import SERVICE_NAME, Resource
      7 from opentelemetry.sdk.trace import TracerProvider

ImportError: cannot import name 'trace' from 'opentelemetry' (unknown location)
```

After manually installing the new deps into my virtualenv:
```python
>>> import chromadb
>>> client = chromadb.HttpClient()
>>> client.create_collection('test1231231232321')
Collection(name=test1231231232321)
```

- [x] Tests pass locally with `pytest` for python, `yarn test` for js

## Documentation Changes
*Are all docstrings for user-facing APIs updated if required? Do we need
to make documentation changes in the [docs
repository](https://github.com/chroma-core/docs)?*