[ENH] Better JS client error messaging (#4944)
This is a simple script that simulates a naive mass upload to Chroma
that will trigger our rate limiter

```
import { CloudClient } from "chromadb";

const client = new CloudClient({
  apiKey: "...",
  tenant: "...",
  database: "test-db",
});

async function run() {
  const collection = await client.getOrCreateCollection({
    name: "ratelimit_test",
  })

  for (let i = 0; i < 100; i++) {
    collection.upsert({
      ids: [i.toString()],
      documents: [`Document ${i}`],
    });
  }
}

run();
```

Users will get a vague "unable to connect" error:

```
/Users/kylediaz/Repos/chroma-core/smokey/node_modules/.pnpm/chromadb@3.0.4/node_modules/chromadb/dist/cjs/chromadb.cjs:1749
  throw new ChromaConnectionError(
        ^


ChromaConnectionError: Unable to connect to the chromadb server. Please try again later.
    at chromaFetch (/Users/kylediaz/Repos/chroma-core/smokey/node_modules/.pnpm/chromadb@3.0.4/node_modules/chromadb/dist/cjs/chromadb.cjs:1749:9)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async o (/Users/kylediaz/Repos/chroma-core/smokey/node_modules/.pnpm/chromadb@3.0.4/node_modules/chromadb/dist/cjs/chromadb.cjs:397:26)
    at async _CollectionImpl.upsert (/Users/kylediaz/Repos/chroma-core/smokey/node_modules/.pnpm/chromadb@3.0.4/node_modules/chromadb/dist/cjs/chromadb.cjs:1644:5) {
  cause: undefined
}

Node.js v22.15.0
```

This PR adds a special error message when hitting a rate limit, and it
shows the response status for all other cases to cover anything we may
have missed