[CHORE] Propogate error messages correctly to user (#4235)
## Description of changes

This PR propogates the error message caught with a modified error
message. It fixes this issue
https://github.com/chroma-core/chroma/issues/3688

previous error message:
```
Traceback (most recent call last):
  File "/Users/jairadhakrishnan/github.com/chroma-core/chroma/chromadb/api/models/CollectionCommon.py", line 95, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jairadhakrishnan/github.com/chroma-core/chroma/chromadb/api/models/CollectionCommon.py", line 233, in _validate_and_prepare_add_request
    add_embeddings = self._embed_record_set(record_set=add_records)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jairadhakrishnan/github.com/chroma-core/chroma/chromadb/api/models/CollectionCommon.py", line 555, in _embed_record_set
    return self._embed(input=record_set[field])  # type: ignore[literal-required]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jairadhakrishnan/github.com/chroma-core/chroma/chromadb/api/models/CollectionCommon.py", line 568, in _embed
    return self._embedding_function(input=input)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jairadhakrishnan/github.com/chroma-core/chroma/chromadb/api/types.py", line 489, in __call__
    result = call(self, input)
             ^^^^^^^^^^^^^^^^^
  File "/Users/jairadhakrishnan/github.com/chroma-core/chroma/chromadb/utils/embedding_functions/openai_embedding_function.py", line 119, in __call__
    response = self.client.embeddings.create(**embedding_params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jairadhakrishnan/github.com/chroma-core/chroma/.venv/lib/python3.12/site-packages/openai/resources/embeddings.py", line 128, in create
    return self._post(
           ^^^^^^^^^^^
  File "/Users/jairadhakrishnan/github.com/chroma-core/chroma/.venv/lib/python3.12/site-packages/openai/_base_client.py", line 1242, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jairadhakrishnan/github.com/chroma-core/chroma/.venv/lib/python3.12/site-packages/openai/_base_client.py", line 919, in request
    return self._request(
           ^^^^^^^^^^^^^^
  File "/Users/jairadhakrishnan/github.com/chroma-core/chroma/.venv/lib/python3.12/site-packages/openai/_base_client.py", line 1023, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.AuthenticationError: Error code: 401 - {'error': {'message': 'Incorrect API key provided: aaask-pr***********************************************************************************************************************************************************gF4A. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jairadhakrishnan/github.com/chroma-core/chroma/test.py", line 85, in <module>
    coll.add(
  File "/Users/jairadhakrishnan/github.com/chroma-core/chroma/chromadb/api/models/Collection.py", line 80, in add
    add_request = self._validate_and_prepare_add_request(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jairadhakrishnan/github.com/chroma-core/chroma/chromadb/api/models/CollectionCommon.py", line 98, in wrapper
    raise type(e)(msg).with_traceback(e.__traceback__)
          ^^^^^^^^^^^^
TypeError: APIStatusError.__init__() missing 2 required keyword-only arguments: 'response' and 'body'
```
the info is all there but the final output is confusing because of this
line
`raise type(e)(msg).with_traceback(e.__traceback__)`

this line is trying to recreate the error with the new message, but does
not track the rest of the arguments in the error. The simplest way to
modify the error message is to recreate e.args with the new error
message

new error

```
Traceback (most recent call last):
  File "/Users/jairadhakrishnan/github.com/chroma-core/chroma/test.py", line 85, in <module>
    coll.add(
  File "/Users/jairadhakrishnan/github.com/chroma-core/chroma/chromadb/api/models/Collection.py", line 80, in add
    add_request = self._validate_and_prepare_add_request(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jairadhakrishnan/github.com/chroma-core/chroma/chromadb/api/models/CollectionCommon.py", line 95, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jairadhakrishnan/github.com/chroma-core/chroma/chromadb/api/models/CollectionCommon.py", line 237, in _validate_and_prepare_add_request
    add_embeddings = self._embed_record_set(record_set=add_records)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jairadhakrishnan/github.com/chroma-core/chroma/chromadb/api/models/CollectionCommon.py", line 559, in _embed_record_set
    return self._embed(input=record_set[field])  # type: ignore[literal-required]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jairadhakrishnan/github.com/chroma-core/chroma/chromadb/api/models/CollectionCommon.py", line 572, in _embed
    return self._embedding_function(input=input)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jairadhakrishnan/github.com/chroma-core/chroma/chromadb/api/types.py", line 489, in __call__
    result = call(self, input)
             ^^^^^^^^^^^^^^^^^
  File "/Users/jairadhakrishnan/github.com/chroma-core/chroma/chromadb/utils/embedding_functions/openai_embedding_function.py", line 119, in __call__
    response = self.client.embeddings.create(**embedding_params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jairadhakrishnan/github.com/chroma-core/chroma/.venv/lib/python3.12/site-packages/openai/resources/embeddings.py", line 128, in create
    return self._post(
           ^^^^^^^^^^^
  File "/Users/jairadhakrishnan/github.com/chroma-core/chroma/.venv/lib/python3.12/site-packages/openai/_base_client.py", line 1242, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jairadhakrishnan/github.com/chroma-core/chroma/.venv/lib/python3.12/site-packages/openai/_base_client.py", line 919, in request
    return self._request(
           ^^^^^^^^^^^^^^
  File "/Users/jairadhakrishnan/github.com/chroma-core/chroma/.venv/lib/python3.12/site-packages/openai/_base_client.py", line 1023, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.AuthenticationError: Error code: 401 - {'error': {'message': 'Incorrect API key provided: aaask-pr***********************************************************************************************************************************************************gF4A. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}} in add.
```

## Test plan
*How are these changes tested?*

- [ ] Tests pass locally with `pytest` for python, `yarn test` for js,
`cargo test` for rust

## Documentation Changes
*Are all docstrings for user-facing APIs updated if required? Do we need
to make documentation changes in the [docs
repository](https://github.com/chroma-core/docs)?*