Update otel-collector-config.yaml
The current configuration leads to the following error:
```
Error: failed to get config: cannot unmarshal the configuration: decoding failed due to the following error(s):

'exporters' the logging exporter has been deprecated, use the debug exporter instead
```
related to https://github.com/open-telemetry/opentelemetry-collector/issues/3524