[BUG] GoogleGeminiEmbeddingFunction cannot be used with Vertex AI enabled (#6676)
## Description of changes

- `api_key_env_var` parameter changed to optional (as stated in method's
docstring)
- removed check that `self.api_key` is not empty
- added check that `self.api_key` and `self.vertexai` are not set
together

## Test plan

### Variables for testing
```Python
VERTEXAI_PROJECT_NAME = "<project>"
VERTEXAI_REGION_LOCATION = "europe-west1"
GOOGLE_APPLICATION_CREDENTIALS_FILENAME = "/<some_path>/vertexai_key.json"

GEMINI_API_KEY="<api_key>"
```

### State before
Running this code:
```Python
import chromadb
from chromadb.utils.embedding_functions import GoogleGeminiEmbeddingFunction
import os

os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = GOOGLE_APPLICATION_CREDENTIALS_FILENAME
os.environ["GEMINI_API_KEY"] = "there is no API key for Vertex AI"
embedding_function = GoogleGeminiEmbeddingFunction(
    model_name="gemini-embedding-001",
    task_type="SEMANTIC_SIMILARITY",
    vertexai=True,
    project=VERTEXAI_PROJECT_NAME,
    location=VERTEXAI_REGION_LOCATION,
    dimension=512,
)

client = chromadb.Client()
collection = client.get_or_create_collection("test", embedding_function=embedding_function)
collection.add(documents=["abc", "test"], ids=["0", "1"])
print(collection.query(query_texts=["testík"], n_results=2))
```
Results in error from `genai` package:
```
ValueError: Project/location and API key are mutually exclusive in the client initializer.
```

### State after
#### Gemini Developer API
```Python
import chromadb
from chromadb.utils.embedding_functions import GoogleGeminiEmbeddingFunction
import os

os.environ["GEMINI_API_KEY"] = GEMINI_API_KEY
embedding_function = GoogleGeminiEmbeddingFunction(
    model_name="gemini-embedding-001",
    task_type="SEMANTIC_SIMILARITY",
    vertexai=False,
    dimension=512,
)

client = chromadb.Client()
collection = client.get_or_create_collection("test", embedding_function=embedding_function)
collection.add(documents=["abc", "test"], ids=["0", "1"])
print(collection.query(query_texts=["testík"], n_results=2))
```
->
```
{'ids': [['1', '0']], 'embeddings': None, 'documents': [['test', 'abc']], 'uris': None, 'included': ['metadatas', 'documents', 'distances'], 'data': None, 'metadatas': [[None, None]], 'distances': [[0.08910208940505981, 0.21813058853149414]]}
```

#### Vertex AI
```Python
import chromadb
from chromadb.utils.embedding_functions import GoogleGeminiEmbeddingFunction
import os

os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = GOOGLE_APPLICATION_CREDENTIALS_FILENAME
embedding_function = GoogleGeminiEmbeddingFunction(
    model_name="gemini-embedding-001",
    task_type="SEMANTIC_SIMILARITY",
    vertexai=True,
    project=VERTEXAI_PROJECT_NAME,
    location=VERTEXAI_REGION_LOCATION,
    dimension=512,
)

client = chromadb.Client()
collection = client.get_or_create_collection("test", embedding_function=embedding_function)
collection.add(documents=["abc", "test"], ids=["0", "1"])
print(collection.query(query_texts=["testík"], n_results=2))
```
->
```
{'ids': [['1', '0']], 'embeddings': None, 'documents': [['test', 'abc']], 'uris': None, 'included': ['metadatas', 'documents', 'distances'], 'data': None, 'metadatas': [[None, None]], 'distances': [[0.08910208940505981, 0.21813058853149414]]}
```

---------

Co-authored-by: propel-code-bot[bot] <203372662+propel-code-bot[bot]@users.noreply.github.com>